// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: stats.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SystemStatsService_ObserveSystemStats_FullMethodName = "/stats.SystemStatsService/ObserveSystemStats"
)

// SystemStatsServiceClient is the client API for SystemStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SystemStatsService — gRPC-сервис с однонаправленным потоком (server streaming).
type SystemStatsServiceClient interface {
	// ObserveSystemStats: клиент передаёт N (send_period) и M (calc_period),
	// сервер периодически отправляет снапшоты, усреднённые за последние M секунд.
	ObserveSystemStats(ctx context.Context, in *SystemStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemStats], error)
}

type systemStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemStatsServiceClient(cc grpc.ClientConnInterface) SystemStatsServiceClient {
	return &systemStatsServiceClient{cc}
}

func (c *systemStatsServiceClient) ObserveSystemStats(ctx context.Context, in *SystemStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemStats], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SystemStatsService_ServiceDesc.Streams[0], SystemStatsService_ObserveSystemStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SystemStatsRequest, SystemStats]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemStatsService_ObserveSystemStatsClient = grpc.ServerStreamingClient[SystemStats]

// SystemStatsServiceServer is the server API for SystemStatsService service.
// All implementations must embed UnimplementedSystemStatsServiceServer
// for forward compatibility.
//
// SystemStatsService — gRPC-сервис с однонаправленным потоком (server streaming).
type SystemStatsServiceServer interface {
	// ObserveSystemStats: клиент передаёт N (send_period) и M (calc_period),
	// сервер периодически отправляет снапшоты, усреднённые за последние M секунд.
	ObserveSystemStats(*SystemStatsRequest, grpc.ServerStreamingServer[SystemStats]) error
	mustEmbedUnimplementedSystemStatsServiceServer()
}

// UnimplementedSystemStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemStatsServiceServer struct{}

func (UnimplementedSystemStatsServiceServer) ObserveSystemStats(*SystemStatsRequest, grpc.ServerStreamingServer[SystemStats]) error {
	return status.Error(codes.Unimplemented, "method ObserveSystemStats not implemented")
}
func (UnimplementedSystemStatsServiceServer) mustEmbedUnimplementedSystemStatsServiceServer() {}
func (UnimplementedSystemStatsServiceServer) testEmbeddedByValue()                            {}

// UnsafeSystemStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemStatsServiceServer will
// result in compilation errors.
type UnsafeSystemStatsServiceServer interface {
	mustEmbedUnimplementedSystemStatsServiceServer()
}

func RegisterSystemStatsServiceServer(s grpc.ServiceRegistrar, srv SystemStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedSystemStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemStatsService_ServiceDesc, srv)
}

func _SystemStatsService_ObserveSystemStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SystemStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemStatsServiceServer).ObserveSystemStats(m, &grpc.GenericServerStream[SystemStatsRequest, SystemStats]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SystemStatsService_ObserveSystemStatsServer = grpc.ServerStreamingServer[SystemStats]

// SystemStatsService_ServiceDesc is the grpc.ServiceDesc for SystemStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.SystemStatsService",
	HandlerType: (*SystemStatsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ObserveSystemStats",
			Handler:       _SystemStatsService_ObserveSystemStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stats.proto",
}
