// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: stats.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SystemStatsRequest — параметры потока статистики.
type SystemStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendPeriod    uint32                 `protobuf:"varint,1,opt,name=send_period,json=sendPeriod,proto3" json:"send_period,omitempty"` // N — интервал отправки снапшотов (сек)
	CalcPeriod    uint32                 `protobuf:"varint,2,opt,name=calc_period,json=calcPeriod,proto3" json:"calc_period,omitempty"` // M — окно усреднения (сек)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStatsRequest) Reset() {
	*x = SystemStatsRequest{}
	mi := &file_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatsRequest) ProtoMessage() {}

func (x *SystemStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatsRequest.ProtoReflect.Descriptor instead.
func (*SystemStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

func (x *SystemStatsRequest) GetSendPeriod() uint32 {
	if x != nil {
		return x.SendPeriod
	}
	return 0
}

func (x *SystemStatsRequest) GetCalcPeriod() uint32 {
	if x != nil {
		return x.CalcPeriod
	}
	return 0
}

// SystemStats — полный снапшот системы.
type SystemStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoadAvg       *LoadAvgStats          `protobuf:"bytes,1,opt,name=load_avg,json=loadAvg,proto3" json:"load_avg,omitempty"`
	Cpu           *CPUStats              `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	DisksLoad     *DisksLoadStats        `protobuf:"bytes,3,opt,name=disks_load,json=disksLoad,proto3" json:"disks_load,omitempty"`
	Filesystems   *FilesystemsStats      `protobuf:"bytes,4,opt,name=filesystems,proto3" json:"filesystems,omitempty"`
	Network       *NetworkStats          `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStats) Reset() {
	*x = SystemStats{}
	mi := &file_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStats) ProtoMessage() {}

func (x *SystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStats.ProtoReflect.Descriptor instead.
func (*SystemStats) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{1}
}

func (x *SystemStats) GetLoadAvg() *LoadAvgStats {
	if x != nil {
		return x.LoadAvg
	}
	return nil
}

func (x *SystemStats) GetCpu() *CPUStats {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemStats) GetDisksLoad() *DisksLoadStats {
	if x != nil {
		return x.DisksLoad
	}
	return nil
}

func (x *SystemStats) GetFilesystems() *FilesystemsStats {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

func (x *SystemStats) GetNetwork() *NetworkStats {
	if x != nil {
		return x.Network
	}
	return nil
}

type LoadAvgStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoadAvg1      float64                `protobuf:"fixed64,1,opt,name=load_avg1,json=loadAvg1,proto3" json:"load_avg1,omitempty"`
	LoadAvg5      float64                `protobuf:"fixed64,2,opt,name=load_avg5,json=loadAvg5,proto3" json:"load_avg5,omitempty"`
	LoadAvg15     float64                `protobuf:"fixed64,3,opt,name=load_avg15,json=loadAvg15,proto3" json:"load_avg15,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadAvgStats) Reset() {
	*x = LoadAvgStats{}
	mi := &file_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadAvgStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAvgStats) ProtoMessage() {}

func (x *LoadAvgStats) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAvgStats.ProtoReflect.Descriptor instead.
func (*LoadAvgStats) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{2}
}

func (x *LoadAvgStats) GetLoadAvg1() float64 {
	if x != nil {
		return x.LoadAvg1
	}
	return 0
}

func (x *LoadAvgStats) GetLoadAvg5() float64 {
	if x != nil {
		return x.LoadAvg5
	}
	return 0
}

func (x *LoadAvgStats) GetLoadAvg15() float64 {
	if x != nil {
		return x.LoadAvg15
	}
	return 0
}

type CPUStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserMode      float64                `protobuf:"fixed64,1,opt,name=user_mode,json=userMode,proto3" json:"user_mode,omitempty"`
	SystemMode    float64                `protobuf:"fixed64,2,opt,name=system_mode,json=systemMode,proto3" json:"system_mode,omitempty"`
	Idle          float64                `protobuf:"fixed64,3,opt,name=idle,proto3" json:"idle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUStats) Reset() {
	*x = CPUStats{}
	mi := &file_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUStats) ProtoMessage() {}

func (x *CPUStats) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUStats.ProtoReflect.Descriptor instead.
func (*CPUStats) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{3}
}

func (x *CPUStats) GetUserMode() float64 {
	if x != nil {
		return x.UserMode
	}
	return 0
}

func (x *CPUStats) GetSystemMode() float64 {
	if x != nil {
		return x.SystemMode
	}
	return 0
}

func (x *CPUStats) GetIdle() float64 {
	if x != nil {
		return x.Idle
	}
	return 0
}

type DisksLoadStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disks         []*DiskLoad            `protobuf:"bytes,1,rep,name=disks,proto3" json:"disks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisksLoadStats) Reset() {
	*x = DisksLoadStats{}
	mi := &file_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisksLoadStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisksLoadStats) ProtoMessage() {}

func (x *DisksLoadStats) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisksLoadStats.ProtoReflect.Descriptor instead.
func (*DisksLoadStats) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{4}
}

func (x *DisksLoadStats) GetDisks() []*DiskLoad {
	if x != nil {
		return x.Disks
	}
	return nil
}

type DiskLoad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Tps           float64                `protobuf:"fixed64,2,opt,name=tps,proto3" json:"tps,omitempty"`
	Kbs           float64                `protobuf:"fixed64,3,opt,name=kbs,proto3" json:"kbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskLoad) Reset() {
	*x = DiskLoad{}
	mi := &file_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskLoad) ProtoMessage() {}

func (x *DiskLoad) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskLoad.ProtoReflect.Descriptor instead.
func (*DiskLoad) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{5}
}

func (x *DiskLoad) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskLoad) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *DiskLoad) GetKbs() float64 {
	if x != nil {
		return x.Kbs
	}
	return 0
}

type FilesystemsStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filesystems   []*FilesystemStats     `protobuf:"bytes,1,rep,name=filesystems,proto3" json:"filesystems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesystemsStats) Reset() {
	*x = FilesystemsStats{}
	mi := &file_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemsStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemsStats) ProtoMessage() {}

func (x *FilesystemsStats) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemsStats.ProtoReflect.Descriptor instead.
func (*FilesystemsStats) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{6}
}

func (x *FilesystemsStats) GetFilesystems() []*FilesystemStats {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

type FilesystemStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Filesystem        string                 `protobuf:"bytes,1,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	MountedOn         string                 `protobuf:"bytes,2,opt,name=mounted_on,json=mountedOn,proto3" json:"mounted_on,omitempty"`
	UsedMb            float64                `protobuf:"fixed64,3,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	UsedPercent       float64                `protobuf:"fixed64,4,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	UsedInodes        float64                `protobuf:"fixed64,5,opt,name=used_inodes,json=usedInodes,proto3" json:"used_inodes,omitempty"`
	UsedInodesPercent float64                `protobuf:"fixed64,6,opt,name=used_inodes_percent,json=usedInodesPercent,proto3" json:"used_inodes_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FilesystemStats) Reset() {
	*x = FilesystemStats{}
	mi := &file_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemStats) ProtoMessage() {}

func (x *FilesystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemStats.ProtoReflect.Descriptor instead.
func (*FilesystemStats) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{7}
}

func (x *FilesystemStats) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *FilesystemStats) GetMountedOn() string {
	if x != nil {
		return x.MountedOn
	}
	return ""
}

func (x *FilesystemStats) GetUsedMb() float64 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *FilesystemStats) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *FilesystemStats) GetUsedInodes() float64 {
	if x != nil {
		return x.UsedInodes
	}
	return 0
}

func (x *FilesystemStats) GetUsedInodesPercent() float64 {
	if x != nil {
		return x.UsedInodesPercent
	}
	return 0
}

type NetworkStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtocolTalkers  []*ProtocolTalker      `protobuf:"bytes,1,rep,name=protocol_talkers,json=protocolTalkers,proto3" json:"protocol_talkers,omitempty"`
	FlowTalkers      []*FlowTalker          `protobuf:"bytes,2,rep,name=flow_talkers,json=flowTalkers,proto3" json:"flow_talkers,omitempty"`
	ListeningSockets []*ListeningSocket     `protobuf:"bytes,3,rep,name=listening_sockets,json=listeningSockets,proto3" json:"listening_sockets,omitempty"`
	TcpStates        []*TCPStateCount       `protobuf:"bytes,4,rep,name=tcp_states,json=tcpStates,proto3" json:"tcp_states,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkStats) GetProtocolTalkers() []*ProtocolTalker {
	if x != nil {
		return x.ProtocolTalkers
	}
	return nil
}

func (x *NetworkStats) GetFlowTalkers() []*FlowTalker {
	if x != nil {
		return x.FlowTalkers
	}
	return nil
}

func (x *NetworkStats) GetListeningSockets() []*ListeningSocket {
	if x != nil {
		return x.ListeningSockets
	}
	return nil
}

func (x *NetworkStats) GetTcpStates() []*TCPStateCount {
	if x != nil {
		return x.TcpStates
	}
	return nil
}

type ProtocolTalker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Bytes         uint64                 `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Percent       float64                `protobuf:"fixed64,3,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolTalker) Reset() {
	*x = ProtocolTalker{}
	mi := &file_stats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolTalker) ProtoMessage() {}

func (x *ProtocolTalker) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolTalker.ProtoReflect.Descriptor instead.
func (*ProtocolTalker) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{9}
}

func (x *ProtocolTalker) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProtocolTalker) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *ProtocolTalker) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type FlowTalker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Bps           float64                `protobuf:"fixed64,4,opt,name=bps,proto3" json:"bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowTalker) Reset() {
	*x = FlowTalker{}
	mi := &file_stats_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowTalker) ProtoMessage() {}

func (x *FlowTalker) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowTalker.ProtoReflect.Descriptor instead.
func (*FlowTalker) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{10}
}

func (x *FlowTalker) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FlowTalker) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *FlowTalker) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *FlowTalker) GetBps() float64 {
	if x != nil {
		return x.Bps
	}
	return 0
}

type ListeningSocket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListeningSocket) Reset() {
	*x = ListeningSocket{}
	mi := &file_stats_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListeningSocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListeningSocket) ProtoMessage() {}

func (x *ListeningSocket) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListeningSocket.ProtoReflect.Descriptor instead.
func (*ListeningSocket) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{11}
}

func (x *ListeningSocket) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ListeningSocket) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ListeningSocket) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ListeningSocket) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ListeningSocket) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type TCPStateCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPStateCount) Reset() {
	*x = TCPStateCount{}
	mi := &file_stats_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPStateCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPStateCount) ProtoMessage() {}

func (x *TCPStateCount) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPStateCount.ProtoReflect.Descriptor instead.
func (*TCPStateCount) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{12}
}

func (x *TCPStateCount) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TCPStateCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_stats_proto protoreflect.FileDescriptor

const file_stats_proto_rawDesc = "" +
	"\n" +
	"\vstats.proto\x12\x05stats\"V\n" +
	"\x12SystemStatsRequest\x12\x1f\n" +
	"\vsend_period\x18\x01 \x01(\rR\n" +
	"sendPeriod\x12\x1f\n" +
	"\vcalc_period\x18\x02 \x01(\rR\n" +
	"calcPeriod\"\x80\x02\n" +
	"\vSystemStats\x12.\n" +
	"\bload_avg\x18\x01 \x01(\v2\x13.stats.LoadAvgStatsR\aloadAvg\x12!\n" +
	"\x03cpu\x18\x02 \x01(\v2\x0f.stats.CPUStatsR\x03cpu\x124\n" +
	"\n" +
	"disks_load\x18\x03 \x01(\v2\x15.stats.DisksLoadStatsR\tdisksLoad\x129\n" +
	"\vfilesystems\x18\x04 \x01(\v2\x17.stats.FilesystemsStatsR\vfilesystems\x12-\n" +
	"\anetwork\x18\x05 \x01(\v2\x13.stats.NetworkStatsR\anetwork\"g\n" +
	"\fLoadAvgStats\x12\x1b\n" +
	"\tload_avg1\x18\x01 \x01(\x01R\bloadAvg1\x12\x1b\n" +
	"\tload_avg5\x18\x02 \x01(\x01R\bloadAvg5\x12\x1d\n" +
	"\n" +
	"load_avg15\x18\x03 \x01(\x01R\tloadAvg15\"\\\n" +
	"\bCPUStats\x12\x1b\n" +
	"\tuser_mode\x18\x01 \x01(\x01R\buserMode\x12\x1f\n" +
	"\vsystem_mode\x18\x02 \x01(\x01R\n" +
	"systemMode\x12\x12\n" +
	"\x04idle\x18\x03 \x01(\x01R\x04idle\"7\n" +
	"\x0eDisksLoadStats\x12%\n" +
	"\x05disks\x18\x01 \x03(\v2\x0f.stats.DiskLoadR\x05disks\"F\n" +
	"\bDiskLoad\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x10\n" +
	"\x03tps\x18\x02 \x01(\x01R\x03tps\x12\x10\n" +
	"\x03kbs\x18\x03 \x01(\x01R\x03kbs\"L\n" +
	"\x10FilesystemsStats\x128\n" +
	"\vfilesystems\x18\x01 \x03(\v2\x16.stats.FilesystemStatsR\vfilesystems\"\xdd\x01\n" +
	"\x0fFilesystemStats\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x01 \x01(\tR\n" +
	"filesystem\x12\x1d\n" +
	"\n" +
	"mounted_on\x18\x02 \x01(\tR\tmountedOn\x12\x17\n" +
	"\aused_mb\x18\x03 \x01(\x01R\x06usedMb\x12!\n" +
	"\fused_percent\x18\x04 \x01(\x01R\vusedPercent\x12\x1f\n" +
	"\vused_inodes\x18\x05 \x01(\x01R\n" +
	"usedInodes\x12.\n" +
	"\x13used_inodes_percent\x18\x06 \x01(\x01R\x11usedInodesPercent\"\x80\x02\n" +
	"\fNetworkStats\x12@\n" +
	"\x10protocol_talkers\x18\x01 \x03(\v2\x15.stats.ProtocolTalkerR\x0fprotocolTalkers\x124\n" +
	"\fflow_talkers\x18\x02 \x03(\v2\x11.stats.FlowTalkerR\vflowTalkers\x12C\n" +
	"\x11listening_sockets\x18\x03 \x03(\v2\x16.stats.ListeningSocketR\x10listeningSockets\x123\n" +
	"\n" +
	"tcp_states\x18\x04 \x03(\v2\x14.stats.TCPStateCountR\ttcpStates\"\\\n" +
	"\x0eProtocolTalker\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x04R\x05bytes\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x01R\apercent\"t\n" +
	"\n" +
	"FlowTalker\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03bps\x18\x04 \x01(\x01R\x03bps\"\x81\x01\n" +
	"\x0fListeningSocket\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\";\n" +
	"\rTCPStateCount\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count2]\n" +
	"\x12SystemStatsService\x12G\n" +
	"\x12ObserveSystemStats\x12\x19.stats.SystemStatsRequest\x1a\x12.stats.SystemStats\"\x000\x01B;Z9github.com/kodmandvl/system-stats-daemon/internal/grpc/pbb\x06proto3"

var (
	file_stats_proto_rawDescOnce sync.Once
	file_stats_proto_rawDescData []byte
)

func file_stats_proto_rawDescGZIP() []byte {
	file_stats_proto_rawDescOnce.Do(func() {
		file_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)))
	})
	return file_stats_proto_rawDescData
}

var file_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_stats_proto_goTypes = []any{
	(*SystemStatsRequest)(nil), // 0: stats.SystemStatsRequest
	(*SystemStats)(nil),        // 1: stats.SystemStats
	(*LoadAvgStats)(nil),       // 2: stats.LoadAvgStats
	(*CPUStats)(nil),           // 3: stats.CPUStats
	(*DisksLoadStats)(nil),     // 4: stats.DisksLoadStats
	(*DiskLoad)(nil),           // 5: stats.DiskLoad
	(*FilesystemsStats)(nil),   // 6: stats.FilesystemsStats
	(*FilesystemStats)(nil),    // 7: stats.FilesystemStats
	(*NetworkStats)(nil),       // 8: stats.NetworkStats
	(*ProtocolTalker)(nil),     // 9: stats.ProtocolTalker
	(*FlowTalker)(nil),         // 10: stats.FlowTalker
	(*ListeningSocket)(nil),    // 11: stats.ListeningSocket
	(*TCPStateCount)(nil),      // 12: stats.TCPStateCount
}
var file_stats_proto_depIdxs = []int32{
	2,  // 0: stats.SystemStats.load_avg:type_name -> stats.LoadAvgStats
	3,  // 1: stats.SystemStats.cpu:type_name -> stats.CPUStats
	4,  // 2: stats.SystemStats.disks_load:type_name -> stats.DisksLoadStats
	6,  // 3: stats.SystemStats.filesystems:type_name -> stats.FilesystemsStats
	8,  // 4: stats.SystemStats.network:type_name -> stats.NetworkStats
	5,  // 5: stats.DisksLoadStats.disks:type_name -> stats.DiskLoad
	7,  // 6: stats.FilesystemsStats.filesystems:type_name -> stats.FilesystemStats
	9,  // 7: stats.NetworkStats.protocol_talkers:type_name -> stats.ProtocolTalker
	10, // 8: stats.NetworkStats.flow_talkers:type_name -> stats.FlowTalker
	11, // 9: stats.NetworkStats.listening_sockets:type_name -> stats.ListeningSocket
	12, // 10: stats.NetworkStats.tcp_states:type_name -> stats.TCPStateCount
	0,  // 11: stats.SystemStatsService.ObserveSystemStats:input_type -> stats.SystemStatsRequest
	1,  // 12: stats.SystemStatsService.ObserveSystemStats:output_type -> stats.SystemStats
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_stats_proto_init() }
func file_stats_proto_init() {
	if File_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_proto_goTypes,
		DependencyIndexes: file_stats_proto_depIdxs,
		MessageInfos:      file_stats_proto_msgTypes,
	}.Build()
	File_stats_proto = out.File
	file_stats_proto_goTypes = nil
	file_stats_proto_depIdxs = nil
}
